### ISSUE TITLE
Pin napalm-base driver

### ISSUE THREAD

**Issue by dbarrosop** [napalm-automation/napalm-base#107]
Make sure we set the latest `napalm-base` version as part of the requirements. The idea is that avoid breaking the guts of the driver without noticing (by changing an internal helper function or the testing framework or something like that).

**Comment by ktbyers** [comment]
I think this is done. The 'snmp', 'iosxr-rpc,' and 'yang' drivers, there is nothing to do. I would close those, but don't have rights.

cc: @dbarrosop @mirceaulinic

**Comment by mirceaulinic** [comment]
Thanks a lot @ktbyers

**Comment by dbarrosop** [comment]
@ktbyers not sure what's going on. You have exactly the same permissions as @mirceaulinic so you should be able to close it as he is. The only difference I can see between his user and yours as the he has 2FA enabled. Not sure if github limits functionality for non-2FA-enabled users. Could you try enabling 2FA and check if you can now close issues?

**Comment by ktbyers** [comment]
@dbarrosop Okay, I have enabled 2FA. I will see if I have any issues going forward.
