### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by dbarrosop** [napalm-automation/napalm-base#109]
See details in the parent issue napalm-automation/napalm#199

**Comment by ktbyers** [comment]
Adding notes regarding pinning napalm-base to 0.17.0.

napalm-ios = DONE
napalm-junos = DONE
napalm-iosxr = DONE
napalm-ros = DONE (as no version of napalm-ros ever released)
napalm-eos = develop, not master
napalm-nxos = develop, not master
napalm-panos = develop, not master
napalm-fortios = develop, not master
napalm-pluribus = develop, not master
napalm-ibm = develop, not master

**Comment by dbarrosop** [comment]
https://github.com/napalm-automation/napalm-fortios/pull/18

**Comment by dbarrosop** [comment]
napalm-eos and napalm-fortios are done.

**Comment by mirceaulinic** [comment]
Also napalm-ibm and napalm-pluribus. Is there anything else we should do before merging https://github.com/napalm-automation/napalm-base/pull/104?

**Comment by mirceaulinic** [comment]
Oh yes, of course: napalm-nxos!

**Comment by ktbyers** [comment]
Yep, napalm-nxos is the last one that I see.

**Comment by mirceaulinic** [comment]
I set the deadline for milestone 0.4.0 for this Friday (hopefully it's a realistic one): https://github.com/napalm-automation/napalm-nxos/milestone/4 as there are two important issues to be addressed.

**Comment by dbarrosop** [comment]
Yay! We are so close : )

**Comment by mirceaulinic** [comment]
napalm-nxos 0.4.0 released - I think everything is prepared now

**Comment by mirceaulinic** [comment]
Closed via https://github.com/napalm-automation/napalm-base/pull/122
