### ISSUE TITLE
Question: add argument `format` for `load_(merge|replace)_config`?

### ISSUE THREAD

**Issue by mirceaulinic** [napalm-automation/napalm-base#111]
At the time being, all config format supported by NAPALM is only ```text```. This is not a problem for OS such as IOS-XR, IOS or EOS, but for JunOS that allows few other formats, e.g.```set```, ```xml``` or ```json``` this constraint becomes a bit uncomfortable.
Right now, for JunOS the format is bespoken as ```text```: https://github.com/napalm-automation/napalm-junos/blob/develop/napalm_junos/junos.py#L118 and does not allow the user at all to change this.
Some folks (including myself) find the ```set``` format more natural and easier to deal with.
Therefore, I would like to add one arg, e.g. ```format```, without having any impact:

```
def load_merge_candidate(self, filename=None, config=None, format='text'):
```

@napalm-automation/council what do you think?

**Comment by ktbyers** [comment]
@mirceaulinic Could we infer it from the filename so we didn't have to change the load_merge/replace_candidate definition. 

It is nice to have consistency of arguments across platforms (or at least minimize any inconsistency).

**Comment by mirceaulinic** [comment]
> Could we infer it from the filename so we didn't have to change the load_merge/replace_candidate definition.

Sure, we can. But the user can also load the config using the ```config``` argument, e.g.:

```python
config = 'set bridge-domains vlan-17 vlan-id 17'
driver.load_merge_candidate(config=config, format='set')
```

> It is nice to have consistency of arguments across platforms (or at least minimize any inconsistency).

I was thinking to propagate this change on all drivers (although most of them won't use this argument at all).

**Comment by ktbyers** [comment]
Good point, yes I like the idea of supporting set and XML formats on Junos, but I think we should maintain argument consistency (at least so the other drivers would accept the argument even if they didn't do anything with it).

**Comment by dbarrosop** [comment]
> I was thinking to propagate the change across all drivers (although most of them won't use this argument at all).

I almost go a stroke... First off, what's the benefit of supporting one format or the other? XML and text has feature parity so it just becomes a "tabs vs spaces" discussion. And in my opinion, adding an argument to a method for the sake of just one driver defeats napalm's agnosticity. I'd be less reluctant if we would pass this as part of an optional argument when creating the object but I still think this is a tab vs spaces fight and we shouldn't even bother with it. What I really don't think we should do is bloat the API with arguments that are used on one driver only and provide no clear value.

**Comment by dbarrosop** [comment]
> Could we infer it from the filename so we didn't have to change the load_merge/replace_candidate definition

I would be fine with this as well.

**Comment by mirceaulinic** [comment]
> First off, what's the benefit of supporting one format or the other?

Flexibility. Actually I do not see any logical reason why we would have this constraint, when the devices have this capability.

> XML and text has feature parity so it just becomes a "tabs vs spaces" discussion.

Nope, it's about providing the users the features they need rather than restricting them to our personal likes or dislikes.

> I'd be less reluctant if we would pass this as part of an optional argument when creating the object 

We'll make the embedded templates unusable as they have ```text``` format only.

> with arguments that are used on one driver only

ATM yes, napalm-junos is the only driver. But napalm-iosxr-rpc will be capable of processing both text and xml. In the future, others will probably need that too.

All we need to do is changing two lines per driver.  If and when we'll agree on this, I can open all the PRs related - should not take more than 30min to do it...

**Comment by dbarrosop** [comment]
> Flexibility

Flexibility is great but it has to serve a purpose other than personal preferences.

> Nope, it's about providing the users the features they need rather than restricting them to our personal likes or dislikes.

Features the need or they want? Because that's two different things and that's why networking sucks. That's why we have stub areas, not so stubby areas and all of those wanker knobs. Vendors need to be able to deploy configuration, they don't need to be able to deploy the same snippet of configuration in 'text', 'xml' and 'set' mode. The latter just becomes a personal preference without any real value.

> Doing so, we'll make the embedded templates unusable as they have text format only.

Should be fairly simple to workaround:

```
self.mode = 'text'
self.load_...
self.mode = 'xml'
```

> napalm-iosxr-rpc will be capable of processing both text and xml

I'd need to see the use case. If there is feature parity between txt and xml I would say I don't care and just deal with one of them and if there is no feature parity, take the one that has all the features and discard the other. We are trying to move away from dealing with vendor shit, clis , etc with things like YANG. Implementing vendor specifics knobs feels like a step backwards to me.

> should not take more than 30min to do it

Sure, that's not the problem. The problem is that I don't want to support vendor specific stuff on any method. I am fine with the optional_args to create the object with some tweaking but I think the API should be completely free of vendor specifics. Otherwise, we can say goodbye to the the second A of NAPALM:

```
if device.vendor == 'iosxr-rpc':
   device.load_...(conf, mode='xml')
elif device.vendor == 'junos':
   device.load_...(conf, mode='set')
```

Why would I use napalm if my code is going to depend on the vendor anyway?

**Comment by dbarrosop** [comment]
I don't want to start here a flame war, I suggest we focus first on the real technical benefits of doing this (including `iosxr-rpc`) trying to put personal preferences aside, then decide if we want to proceed based on that information and then how to proceed.

**Comment by mirceaulinic** [comment]
> I don't want to start here a flame war

That's daylight clear, nobody has this intention :) But we can discuss and eventually change it for the better.

> Flexibility is great but it has to serve a purpose other than personal preferences.

Alright, don't want to be misunderstood: this library does and should not depend on any externals. But I will give you the example of my colleagues that are able to select all devices running Junos and load a couple of config lines, without loosing their eyes in curly brackets (as forced by the text format). This is because we have this feature in our internal napalm (yes, their diverged a lot).
What I mean is that perhaps other engineers would find that useful too.

> Should be fairly simple to workaround:

It's still a workaround - why not keep it straight and simple?

```python
self.mode = 'text'
self.load_...
self.mode = 'xml'
```

Doing so, we'll forever force the template format to be as text. But why not allow the user decide what's the most comfortable for them?

> Otherwise, we can say goodbye to the the second A of NAPALM

I see you point and totally agree with you. But this won't break anything IMHO, would just add one extra feature and is not like the text will be no longer supported :)

> Because that's two different things and that's why networking sucks. 

I have many things to say about that anyway :)

**Comment by dbarrosop** [comment]
> without loosing their eyes in curly brackets

Not sure what you mean with that. Care to elaborate? Are you implying xml is easier for people to deal with than json-like syntax? Which again, it's a personal preference, not a technical reason. 

> select all devices running Junos and load a couple of config lines

How is that different from parallel ssh? Why can't you build that same tool with an optional_arg that tells the tool you want to use XML for that particular session?

> It's still a workaround - why not keep it straight and simple?

That was a workaround for embedded templates, so users would hopefully never do that. For the embedded templates we could also base it on the file extension as @ktbyers suggested, which I think is a great idea.

> would just add one extra feature and is not like the text will be no longer supported :)

Sure, I am not against the feature, I am happy adding an optional arg or discover the format with the file extension. What I am opposing to is changing the API to accommodate one use case that doesn't really bring any technical value, it just accommodates personal preferences. I am also against bloating the API with optional args that only works for certain devices on certain methods. One thing that people likes about napalm is that is quite straightforward to use, if we bloat the API we are going to lose that simplicity.

**Comment by mirceaulinic** [comment]
> Not sure what you mean with that. Care to elaborate? Are you implying xml is easier for people to deal with than json-like syntax?

No, I mean the difference between text and set:

- text:

```
protocols { bgp { group my-group { neighbor 1.2.3.4 { family inet { unicast { prefix-limit { delete: maximum; }}}}}
```

- set:

```
delete protocols bgp group my-group neighbor 1.2.3.4 family inet unicast prefix-limit maximum
```

Do you see what I mean now? Can you follow the curly brackets with ease?

Also: I think this annoying ```text``` format does not allow the very handy ```copy```, ```insert before```, ```insert after```, ```move```, ```rename``` or ```replace``` features - I did not find a way. And I searched! Only this argument I think should be enough!

> For the embedded templates we could also base it on the file extension as @ktbyers suggested, which I think is a great idea.

That is available for static config files that can have the extension ```.json```, ```.xml```, ```.txt``` and based on this we can determine the config-type. The templates are ```.j2``` - how would you use this to identify?

> Why can't you build that same tool with an optional_arg that tells the tool you want to use XML for that particular session?

Again, because the templates would become unusable.
Imagine opening the sessions, passing the ```optional_arg``` as ```set```, for example. When loading the config, will render the template (in ```text``` format) and will try to load it as ```set```. Error.

P.S.: the text format above is wrong and any human would probably miss the missing curly bracket at the end and loading that config, of course, will fail!

**Comment by dbarrosop** [comment]
> Do you see what I mean now? Can you follow the curly brackets with ease?

Sure,  but if you want to run ad-hoc commands, why aren't you using the `run_commands` method?

> I think this annoying text format does not allow the very handy copy, insert before, insert after, move, rename or replace

It can be done, there is feature parity. Here is an example:

https://github.com/dravetech/network-tutorials/blob/master/tutorial-6-abstractions/roles/ipfabric/templates/junos/ipfabric.j2#L4

> The templates are .j2 

Templates can have any extension so we can accommodate the extension.

> Again, because the templates would become unusable

See above.

> the text format above is wrong and any human would probably miss the missing curly bracket at the end and loading that config, of course, will fail!

I don't think this use case requires any changes in napalm. You just built a wrapper for the CLI so `run_commands` method should cover it (a network specific `pssh` ;) ).

**Comment by mirceaulinic** [comment]
> Sure, but if you want to run ad-hoc commands, why aren't you using the run_commands method?

Not sure what you mean... what is ```run_commands``` again?

> Templates can have any extension so we can accommodate the extension.
Again, because the templates would become unusable
See above.

I think we are going circles here. So you'd prefer a hack rather than keeping things simple, right?

All I can see is that you are trying to force defining all templates in ```text``` type format.

> You just built a wrapper for the CLI so run_commands method should cover it

CLI supports show-type commands only. Are you still on topic?

If we want to reduce the supported capabilities, on the long term more and more people will complain about that. I think the feedback from my colleagues should be good enough - right now  ```load_merge_config``` is pseudo-usable for junos devices as nobody wants to type those curly brackets on the fly.

**Comment by dbarrosop** [comment]
Ok, I am going to back out for a second. I am going to try to summarize your use case, give you the reason why I was a bit reluctant to your use case, why I think there is still value on supporting it and propose a solution.

**Use case**: Use napalm to write a tool to run adhoc commands on devices. You could easily write this tool with `pyez` because you don't need/want any vendor abstraction capability here but you feel comfortable with `napalm` so you want to do it with `napalm`. `napalm` also allows you to reuse the same script for other vendors. The tool will never be able to deal with multiple vendors at a time but at least the same tool will work with different vendors at different times.

**Reluctancy**: What you are building is a script it's designed to work ONLY with one vendor. A parallel ssh of the sorts. That tool could never work with multiple vendors at a time as NAPALM was original intended. This defeats the purpose of NAPALM. However, I understand for users it might be a pain in the ass to use napalm for some stuff and `pyez/pyeapi/pywhatever` for others so I think there is value on providing this functionality. Keeping users in the house ;)

**Proposed solution**: Implement a `run_commands` or `adhoc_commands`  or something like that that let's you send an arbitrary list of commands to a particular device. For example, the junos implementation could be something like:

```
def adhoc_commands(self, commands, **kwargs):
    " Commands is a list of commands"
    if commands[0] == "configure":
        # code to send set commands to the device or even use **kwargs to do some tweaks, this method is completely tied to particular vendors so we can have a similar approach as with the optional_args
    else:
       for command in commands:
            self.device.cli(command, **kwargs)
```

For `eos` it could be:

```
def adhoc_commands(self, commands, **kwargs):
     self.device.run_commands(commands, **kwargs)
```

The reason of building it like this it's because then we have a clear separation on which methods are `AGNOSTIC` and which ones are not. I like having this clear definition. In addition to this new method, if we still want to support the optional argument to set the session as `set/xml/text` I am fine with that too.

Thoughts? Does this seems like a good middle ground?

**Comment by mirceaulinic** [comment]
>  Use napalm to write a tool to run adhoc commands on devices.

Not a separate tool, as would be pointless to use something else, when another process has already a session already open and waiting for you to deliver data. But yes, running arbitrary commands when needed, against devices, grouping them by vendor/OS.

To give a bit more of context, is when you need to configure something very quick and straightforward. Dummy example:

```bash
$ sudo salt -N junos net.load_config format='set' text='set system ntp peer 172.17.17.1'
```

And that's how we set a NTP peer on a couple of hundreds of devices. I know you believe only in render template -> load replace, but that's a different use case :P Some people find it handy, others don't, as some people like green others blue :)

> What you are building is a script it's designed to work ONLY with one vendor. 

Correct, at a specific time, will be against one single vendor. Next command is against a different vendor and so on.

> A parallel ssh of the sorts.

Exactly. But using the session already open through napalm.

> That tool could never work with multiple vendors at a time as NAPALM was original intended. This defeats the purpose of NAPALM

As previously said, I do understand your point and totally makes sense. But as you also said, would avoid using a different lib, especially when something is already in use.

> Proposed solution: Implement a run_commands or adhoc_commands or something like that that let's you send an arbitrary list of commands to a particular device. For example, the junos implementation could be something like:

In theory sounds good to me.

How about the following header?

```python
def adhoc_commands(self, commands, configure=False, **kwargs):
```

But what would you have in:

```python
# code to send set commands to the device or even use **kwargs to do some tweaks, this method is completely tied to particular vendors so we can have a similar approach as with the optional_args
```

My understanding is that would contain parts from ```_load_candidate``` https://github.com/napalm-automation/napalm-junos/blob/develop/napalm_junos/junos.py#L104-L123, example for ```junos``` which basically means we'll have duplicate code.

I still believe that adding one extra arg won't hurt that much and would also avoid redundant code.

**Comment by dbarrosop** [comment]
```
def adhoc_commands(self, commands, configure=False, **kwargs):
```

Looks good to me.

> I still believe that adding one extra arg to load_merge_config won't hurt that much and would also avoid redundant code.

For the particular case of `junos` we can just do the following:

```
def _ load_merge_config(self, [all the parameters we need]):
    # code we had before on load_merge_config

def load_merge_config(self, config, etc..):
   self._load_merge_config(...)
```

We can revisit this later on if we get a more interesting use case but for the sake of yours I think it makes more sense the proposed solution. It also give us some other nice features that people has commented on in the past.

**Comment by mirceaulinic** [comment]
@dbarrosop I just realised that we discussed so much about that and we missed an essential detail - basically we were unable to see the woods because of the trees.

By definition the method ```load_merge_config``` itself cannot be vendor agnostic. All existing arguments make it like that. You cannot pass the same argument (either ```config```, either ```file```) across all drivers by no means. Therefore it is already non-vendor agnostic.

With these said, I think my proposal still stands, as would not change at all this behaviour - and would also be the less painful to introduce. Please let me know what you think.

**Comment by ktbyers** [comment]
```
By definition the method load_merge_config itself cannot be vendor agnostic. All existing arguments make it like that. You cannot pass the same argument (either config, either file) across all drivers by no means. Therefore it is already non-vendor agnostic.
```

I think this is conflating the arguments from the value of the arguments. The arguments are the same what the contain is different.

What if we do the following?

```
     def load_merge_candidate(self, filename=None, config=None):
```

If "filename" infer the type from the filename extension. Follow juniper conventions here.

If "config", then default to 'conf'. If you want to support a different type, add a header string as a juniper comment or as a string formatted a specific way that will be removed from the 'config'.

This would allow us to keep the method definition unchanged and support the three file types.

I am interested in supporting XML as I have heard with Juniper that you can have problem with older devices using conf format and trying to do config replace/merge operations. I heard this second hand and haven't verified it myself, but the person I heard this from was testing this quite a bit (at the time).

We could front a CLI tool with something that added the necessary header info.

**Comment by mirceaulinic** [comment]
> If "filename" infer the type from the filename extension. Follow juniper conventions here.

Yes, we all agreed on this - that's somehow natural.

>  If you want to support a different type, add a header string as a juniper comment or as a string formatted a specific way that will be removed from the 'config'.

In principle this sounds good.

But how do you define those comments and make sure that loading on the device won't fail even if they still remain there?

I tried:

```
# load set terminal
[Type ^D at a new line to end input]
/* just a comment */

terminal:1:(0) unknown command: /*
load complete
```

Doesn't seem to like.

The way you can introduce comments on Junos is:

```annotate <stanza> "<your comment>"```

```
# load set terminal
[Type ^D at a new line to end input]
annotate system "just a comment"

load complete
```

```
# show
## Last changed: 2016-10-28 09:22:52 UTC

/* just a comment */
system {
```

And introducing a requirement like that, I'm not sure that is quite optimal.

We could try to match the first line in ```config```, looking for something like ```# format: <format>``` - but this is again a hack.

**Comment by dbarrosop** [comment]
> I have heard with Juniper that you can have problem with older devices using conf format and trying to do config replace/merge operations.

That would be a valid reason and I would love to support xml and set modes if that's true. I have used napalm with JunOS as old as 12.x without any problem but that doesn't mean much. Actually, all my demos are running firefly which is based off 12.1 and never run into issues with replace or merges and even partial replaces work flawlessly. Do you think you could get more information?

In any case, I think we are overdoing it. If we want to implement this I would like to see the use case and depending on the use case it could be as simple as using an `optional_arg` and set the type of config for the session. If people wants to mix different types in the same session I would like to see the technical reason for that. I think features don't have to be provided "because we can" but "because they are useful".

**Comment by mirceaulinic** [comment]
> If people wants to mix different types in the same session I would like to see the technical reason for that.

I will do it step by step, with a trivial example.

Say ```config_format``` is the optional arg in cause.

```python
from napalm_base import get_network_driver
driver = get_network_driver('junos')
instance = driver(<host>, <usr>, <pass>, optional_args={'config_format': 'set'})
instance.open()

instance. load_merge_candidate(config='set system name-server 8.8.8.8')  # works fine

instance. load_template('set_hostname', hostname='my.hostname')  # FAIL
```

And will be two errors, out of three loaded lines:

- unknown command: system
- unknown command: host-name

Is the failure of a feature we currently have enough technical reason @dbarrosop?

**Comment by dbarrosop** [comment]
i don't know at this stage if you are jus trolling me or what ;) You keep coming to this issue. I still don't understand why you think this will be an issue. As I said previously, we can infer the type by the extension file as @ktbyers suggested, we can also make sure the `load_template` uses the correct type ourselves as we provide both the code and the template... we can do many things to make sure that will not be an issue. Nobody wants to break anything or remove functionality. The config_format as I suggested would just be used for:

1. If the user passes the configuration in the `config` argument.
2. If the extension of the file doesn't tell us anything.

So in your example, all the code would work perfectly fine.

**Comment by mirceaulinic** [comment]
> As I said previously, we can infer the type by the extension file as @ktbyers suggested, we can also make sure the load_template uses the correct type ourselves as we provide both the code and the template... we can do many things to make sure that will not be an issue.

Yes... unfortunately I think there are too many things to do to avoid this:


- enhance the ```load_template``` helper to handle different formats, would probably be something like ```<template_name>.<config_format>.j2```, e.g.: ```set_hostname.text.j2```
- propagate this into all drivers and rename all files
- for junos provide the same functional template in different formats: ```set_hostname.set.j2```, ```set_hostname.text.j2```, ```set_hostname.xml.j2``` and ```set_hostname.json.j2``` etc. to ensure functionality.

Is there anything I'm missing?

**Comment by mirceaulinic** [comment]
> load_template uses the correct type ourselves as we provide both the code and the template

No, we don't provide the template - only some small ones.

How about:

File is called: ```/path/to/my/template/junos/templates/my_custom_template.j2```

```python
instance.load_template('my_custom_template', template_path='/path/to/my/template/', ...some vars)
```

Or would you like to do:

```python
instance.load_template('my_custom_template.set', template_path='/path/to/my/template/', ...some vars)
```

where file is: ```/path/to/my/template/junos/templates/my_custom_template.set.j2```?

**Comment by dbarrosop** [comment]
I suggest the following:

1. We rename our template to `name_of_template.text`. We don't really need the `j2` extension for any reason whatsoever.
2. We patch `JunosDriver._load_candidate` to use either the extension of the file or the `config_format` in case the configuration was passed in the `config` argument or the extension of the file is generic so we can't infer anything.

This will give us exactly the functionality we are discussing with very little change. And the best is that all change is within the Junos driver, which means there will be no side effects anywhere.

**Comment by mirceaulinic** [comment]
> We rename our template to name_of_template.text. We don't really need the j2 extension for any reason whatsoever.

True

> We patch JunosDriver._load_candidate to use either the extension of the file or the config_format in case the configuration was passed in the config argument or the extension of the file is generic so we can't infer anything.

Sounds good, indeed would be much easier like that.

**Comment by dbarrosop** [comment]
Ok, I just realized it's not that simple because of this:

https://github.com/napalm-automation/napalm-base/blob/develop/napalm_base/helpers.py#L62

We will have to find a way of fixing that. Probably replacing that line with some helper method that tries to find the template trying different extensions.

I think we got a nice idea to solve this. I suggest to close this issue, open another one with a summary of what we want to build, reference to this one and do it at some point. I don't think this is so critical but I am sure some people will like it. We will need another issue to track the new method we came up with here; `run_commands`. @mirceaulinic do you want to take care of creating the issues and proposing the new method definition?

**Comment by mirceaulinic** [comment]
> Ok, I just realized it's not that simple because of this:
https://github.com/napalm-automation/napalm-base/blob/develop/napalm_base/helpers.py#L62

Yes, but I guess would not be that hard to adjust.

> I think we got a nice idea to solve this.

I think so too :)

> I don't think this is so critical but I am sure some people will like it. 

Not at all urgent - all the ideas I am exposing these days are just some small features for the very long run anyway - BTW I'm not done yet, I still have a couple, sorry.

>  @mirceaulinic do you want to take care of creating the issues and proposing the new method definition?

Sure, will do it later today.

**Comment by dbarrosop** [comment]
> Sure, will do it later today 

Thanks! My priority right now is the YANG and testing frameworks so I have my hands full with just that.

**Comment by jedelman8** [comment]
BTW, this is something we (@ggabriele) tried to do too when PANOS was being built too :)  

It's very Juniper-like and IIRC, load_replace_candidate can only be XML and load_merge_candidate can only be set syntax.  Using file extensions would be nice, but think Gabriele ended up just inferring what it was and raising an error so the user would know if it wasn't correct.

**Comment by mirceaulinic** [comment]
Opened https://github.com/napalm-automation/napalm-base/issues/117 and https://github.com/napalm-automation/napalm-base/issues/118 as per discussion in this thread.
Additionally: https://github.com/napalm-automation/napalm-junos/issues/70 and https://github.com/napalm-automation/napalm-junos/issues/71 as napalm-junos is the only NAPALM driver that currently needs some slight adjustments.
