### ISSUE TITLE
Question: default values

### ISSUE THREAD

**Issue by mirceaulinic** [napalm-automation/napalm-base#114]
I have noticed another inconsistency in terms of default values when some fields cannot be filled with a corresponding value (for various reasons, e.g.: not provided by the vendor, inconsistent value - sometimes , for the same field a stupid vendor returns str or int etc.).

When this happens, we need to return a value though. For string is pretty obvious - returning empty value; for bool I think the right thing is `False` in most of the cases. But how about `int` or `float`? Do you think we should/can keep this homogenous?

Eventually we could define a new module under `napalm-base`, e.g.: `defaults.py` and define a hash such:

``` python
map = {
  str: u'',
  int: -1,
  float: -1.0
}
```

@napalm-automation/council what do you think?

**Comment by mirceaulinic** [comment]
And using the ```py23_compat```https://github.com/ktbyers/napalm-base/blob/ae9b04e6b4d85d56fdd9c9e64b782af44bb16ddd/napalm_base/utils/py23_compat.py  would be even better I guess.

**Comment by ktbyers** [comment]
The default values should be defined in the getter documentation (in napalm-base) and then enforced by the unit tests (if they matter). In other words, where ever we define what the getter should return is where the default values should be specified.

If I was writing a getter, that would be where I would look. In general, I don't really like importing things from napalm-base (for very minor things) as I think it introduces an unnecessary level of indirection. Frequently, this makes something that would be obvious not obvious; then I have to dig into napalm-base to see...oh that is just setting this to a null string.

**Comment by mirceaulinic** [comment]
> The default values should be defined in the getter documentation (in napalm-base) and then enforced by the unit tests (if they matter). In other words, where ever we define what the getter should return is where the default values should be specified.

Totally makes sense, agreed it would be easier.

> If I was writing a getter, that would be where I would look. In general, I don't really like importing things from napalm-base (for very minor things) as I think it introduces an unnecessary level of indirection.

I see your concern, but I don't consider this as a real issue as anyway napalm-base is a dependency.

> Frequently, this makes something that would be obvious not obvious; then I have to dig into napalm-base to see...oh that is just setting this to a null string.

I was thinking something more like:


```python
>>> my_raw_value = 'totally wrong'
>>> napalm_base.helpers.convert(float, my_raw_value)
-1.0
```

And you don't need to look anywhere, the ```convert``` function will try to convert to ```float``` and if it fails, will return the default value for this datatype.

**Comment by ktbyers** [comment]
@mirceaulinic It is not about dependencies. It is about code readability. 

Having to go look up napalm_base.helpers.convert() to figure out what you are doing is IMO worse, than the problem. Once you know the pattern it is fine, but looking at the above code without an existing context I would be surprised that the convert() method would typecast a string to a float with a value of '-1'.

Also the above pattern would have the tendency to hide errors which I think would make NAPALM worse in the long run i.e. the getter is not even returning the right data type. We probably shouldn't be hiding this.

**Comment by mirceaulinic** [comment]
@ktbyers Can't agree more. Let's see what @dbarrosop thinks about that - he has a better idea with classes.

**Comment by dbarrosop** [comment]
So, I had also been thinking about this due to the YANG work I am [slowly] doing. I think the best solution is something like this:

1. `None` for not yet populated methods.
2. `constants.NotSupported` for unsupported methods. `constants.NotSupported` should also evaluate `False`.

That way we could do things like:

```
if results['whatever'] is None:
  # some code to populate the field

if results['whatever'] is constants.NotSupported:
   print("this is not supported"):

or:

if results['whatever']:
   # I have valid date, if we use -1 or something might make the code believe it's supported even though it's not, if we use 0, we might not be able to distinguish between 0 as a real value and 0 as an unsupported field.
```

Does this make sense?

**Comment by mirceaulinic** [comment]
@dbarrosop I understand you propose to return -1 as default for int (which implies -1.0 for float). Totally agree - actually that was my biggest concern (should be -1 or 0, and I was also tempted to pick the first).
For the rest (bool, text_type or list) is trivial.

Few questions:

- the checks you presented above should be made at the end of the method, before returning the output? Or an external module that compares with the datatype from https://github.com/napalm-automation/napalm-base/blob/develop/napalm_base/test/models.py and will make sure to return the right datatype?

- what do you expect to be:

```python
if results['whatever'] is constants.NotSupported:
````

What is ```constants.NotSupported```? Example?

P.S.: I updated your previous comment and split the inline comment into multiple

**Comment by dbarrosop** [comment]
Sorry for the late resposne.

Those were just examples to show use cases, not really meant to be tests or anything.

**Comment by mirceaulinic** [comment]
I am looking at this and not only that I don't remember what I understood, but I'm still not sure what you mean @dbarrosop?

**Comment by dbarrosop** [comment]
haha! The idea was to use custom objects to indicate the state of a value rather than encoding it on the value:

1. `None` for not yet populated variables, so they have to be populated.
1. `constants.NotSupported` for unsupported variables. `constants.NotSupported` should be a singleton that also evaluates `False`.

**Comment by dbarrosop** [comment]
I guess we can close this one, right?

**Comment by mirceaulinic** [comment]
Yes, we can close.
