### ISSUE TITLE
Question: dry-run and debug mode for the load_template method

### ISSUE THREAD

**Issue by mirceaulinic** [napalm-automation/napalm-base#115]
Yet another proposal from my series of small handy features.

When using the `load_template` method, you know the template structure, but sometimes the result may be unknown, unexpected etc. and you don't know where to start looking from.
At the end of the day it is just a piece of software and the question `Why this shit does not work? Is should!` will come up sooner or later.

Whilst using it, I have identified two useful features:
- debug: return the result of the rendered template, without trying to load on the device
- dry run: load on the device -> compare config -> discard and return the diff

Changes implied: 
- ATM the output of `load_template` is `None`, would be changed to `str`.
- add two arguments defaulting to false: `test` (for dry run) and `debug` (you guessed - for debug)

``` python
def load_template(cls, template_name, template_source=None, template_path=None,
                  openconfig=False, test=False, debug=False, **template_vars):
```

@napalm-automation/council  thoughts?

**Comment by dbarrosop** [comment]
* `debug` That should probably be a best practice in general, use `logging.{debug, info, critical}` statements in key places and let uses configure those with env. variables or tweaking the logging configuration in their code. So I wouldn't use that as part of the signature but as part of the libraries in general. For example, it could be useful to print the raw data we are using for the getters if `debug` is enabled.

* `dry-run`. That's exactly how it works today, right? Not sure what's the functionality you want to add here. `load_template` it's a wrapper around `load_merge_candidate`, which means your code still has to do the `compare_config`, `discard`, `commit`, etc... For example:

```
device.load_template('ntp', my_data)
print(device.compare_config())
device.discard()
```

What are you missing on the dry-run case? Or did I misunderstand something?

**Comment by mirceaulinic** [comment]
Sorry about dry-run. I got a bit confused looking at our version - you are perfectly right, this is how it is today.

> debug That should probably be a best practice in general, use logging.{debug, info, critical} statements in key places and let uses configure those with env. variables or tweaking the logging configuration in their code. So I wouldn't use that as part of the signature but as part of the libraries in general. For example, it could be useful to print the raw data we are using for the getters if debug is enabled.

I agree, this would be better. Definitely from a software dev perspective would make more sense. But from an unexperienced CLI user, sometimes it is more useful to see real-time what the method tried to load, rather than looking in the logs and trying to figure out what actually happened. Especially when you have much data recorded. What do you think?

**Comment by mirceaulinic** [comment]
As per our slack conversation, this is moot - no need to do it :)
