### ISSUE TITLE
Use unicode instead of str in models.py

### ISSUE THREAD

**Issue by DiogoAndre** [napalm-automation/napalm-base#116]
Most models in [models.py](https://github.com/napalm-automation/napalm-base/blob/develop/napalm_base/test/models.py) are already using `unicode` instead of `str`.  `users` and `config` are still using `str`, as bellow:

```python
users = {
    'level': int,
    'password': str,
    'sshkeys': list
}

config = {
    'running': str,
    'startup': str,
    'candidate': str,
}
```

Shouldn't we just use `unicode` wherever any kind of text return is expected? 

I bumped into this when implementing the `get_config` method for IOS. The [TestIOSDriver.py](https://github.com/napalm-automation/napalm-ios/blob/develop/test/unit/TestIOSDriver.py) returns `unicode` when reading from mock data files, and it causes the `assert self._test_model` test  to fail.

**Comment by mirceaulinic** [comment]
Hi @DiogoAndre,

There's no reason why it is ```str```, other than _mistake_.

We are already planning some changes in the structure of the models and the datatypes: https://github.com/napalm-automation/napalm-base/pull/104 and this will be also covered.

**Comment by ktbyers** [comment]
@DiogoAndre Yes, this issue is all fixed with Python3 support (i.e. all strings become unicode) so it will go away when napalm-base has Py3 support which should be soon.
