### ISSUE TITLE
Implement `run_commands` method

### ISSUE THREAD

**Issue by mirceaulinic** [napalm-automation/napalm-base#117]
As per https://github.com/napalm-automation/napalm-base/issues/111, in order to ease the execution of arbitrary commands (both oper and config type) on devices grouped by vendor/os, we will need to implement a new method `run_commands`.

The body should be similar to:

``` python
def run commands(self, commands, config=False, **kwargs):
    " Commands is a list of commands"
    if config:
        # code to send set commands to the device or even use **kwargs to do some tweaks, this method is completely tied to particular vendors so we can have a similar approach as with the optional_args
    else:
       for command in commands:
            self.device.cli(command, **kwargs)
```

**Comment by dbarrosop** [comment]
I knew there was something like this already:

https://github.com/napalm-automation/napalm-base/blob/develop/napalm_base/base.py#L546

**Comment by mirceaulinic** [comment]
Yes and would be reused in ```run_commands``` to execute raw operational commands.

**Comment by mirceaulinic** [comment]
> We can probably just adapt the signature and rewrite the code, no need of having cli and run_commands.

I guess to do so we'd need to add one extra argument, which is the same discussion we had in https://github.com/napalm-automation/napalm-base/issues/111 but for a different method...

**Comment by dbarrosop** [comment]
Yeah, I am fine with that. Just let's make sure the default behavior doesn't change and that's it.

**Comment by mirceaulinic** [comment]
Closing as per https://github.com/napalm-automation/napalm-base/issues/172
