### ISSUE TITLE
Allow to not set a password

### ISSUE THREAD

**Issue by vincentbernat** [napalm-automation/napalm-base#144]
Hey!

When using SSH key, asking for a password is not needed. Also, with an appropriate SSH configuration, we shouldn't override the user either. I suggest to set the default user to `None` if possible (for JunOS, py-eznc will use the current user if it doesn't find anything better).

**Comment by mirceaulinic** [comment]
Hi @vincentbernat - we had a similar discussion some time ago: see https://github.com/napalm-automation/napalm-panos/pull/23#discussion_r85711073

I am into allowing the authentication using SSH key, but in the same time we need to keep in mind that NAPALM must be flexible across all drivers (including those that do not allow SSH key and other features). 

Unfortunately your proposal to allow username and/or password defaulting to None is not currently possible.

But we can (read: should) allow ssh keys! This would be done via an optional arg.

Thoughts?

**Comment by dbarrosop** [comment]
Ssh keys work out of the box, at least for junos, just specify the correct username, and set the password as empty. The key will be picked by the underlying driver automatically. Custom locations for ssh keys are currently not supported though.

**Comment by vincentbernat** [comment]
Yes, in fact, I noticed that after. I can set `--password ""` and everything works as expected. I understand the rationale. Let's close this bug.

**Comment by vincentbernat** [comment]
As for SSH keys, in the case of the JunOS backend, this can be provided with:

 - the proper entry in `~/.ssh/config` (or a file specified with `ssh_config` parameter)
 - the `ssh_private_key_file` option

Maybe it would be nice to have something unified for all backends, but as far as I am concerned, I would expect all backends to be able to use `~/.ssh/config` (which can be used easily with Paramiko), so I wouldn't use this option myself.

**Comment by dbarrosop** [comment]
Yeah, I agree with you and it should work as you explain. Otherwise, feel free to open a new issue so we can take a look.
