### ISSUE TITLE
Proposal: new `community` branch

### ISSUE THREAD

**Issue by mirceaulinic** [napalm-automation/napalm-base#182]
We sometimes see people asking about features that are not quite cross-vendor, such as EIGRP, CDP or FEX.
Of course (and I'm already seeing David typing the reply) this is against the NAPALM philosophy - I totally agree with this. But at the same time I do see the value added having these features.
I personally know people using `napalm-junos` just because it's way easier to just execute `pip install napalm-junos` and then get the BGP configuration with one call rather than rewriting the YAML descriptors for `junos-eznc`.
So, besides it's vendor abstraction, NAPALM is also about features/getters.
But some vendors have their proprietary protocols and people are interested in them. And I think we could support them, especially when people want to bring their contribution back to the community.
With these said, I think we could create a separate branch, say `community` where vendor-specific getter would go. No release needed, or we could release a `rc` version - not the official one.
This will bring a bit of complexity, but not much - providing some extra support for the community.

Thoughts?

**Comment by dbarrosop** [comment]
Using your examples:

* CDP is just another way of getting neighbors so it should be integrated with `get_lldp_neighbors`. If LLDP is not enabled, fallback to CDP on devices that support it.
* EIGRP, why do you need a method for that? It will depend on what you want to do. If you want to get routes we could easily add support to the protocol on `get_route_to`

In any case, I'd rather try to make things generic and vendor-agnostic, as I sincerely don't think that there are that many "vendor-specific"  commands (maybe qfabric, VSS o other crap like that). In cases where there is no way to make it agnostic, I think I'd prefer to have them as part of the main branch than having to track two different branches. Naming of those methods should clearly indicate is a vendor-specific method. For example, `junos_get_qfabric` or `ios_get_vss`.

**Comment by mirceaulinic** [comment]
> In cases where there is no way to make it agnostic, I think I'd prefer to have them as part of the main branch than having to track two different branches. Naming of those methods should clearly indicate is a vendor-specific method. For example, junos_get_qfabric or ios_get_vss.


Yes, this sounds sane to me.

Before closing this topic, where do you think it would be the right place for the tests? I think we could extend the local tester, under the driver implementing the method in cause.

**Comment by dbarrosop** [comment]
Mmmm, I think I'd need to do some tests here on how to best do it. I think it makes sense to have them on a dedicated file on the driver itself. Let's do something, first time we have a vendor-specific method implementation we do it against a branch and we see how to best integrate it with the testing framework and how to generate the documentation automatically.

**Comment by mirceaulinic** [comment]
Yeah.. this might be pretty problematic.

I was thinking now also about documentation: as this is triggered based on the methods tested with the tests from napalm-base, I think we should do the same with driver-specific getters. As of today we consider all methods that have the prefix `get_`, we could as well test also `$driver_` and generate doc. Do you think that would be a bit overkill?

**Comment by dbarrosop** [comment]
> As of today we consider all methods that have the prefix get_, we could as well test also $driver_ and generate doc. Do you think that would be a bit overkill?

Yeah, that's exactly why I wanted to name them `$driver_get`. It works for humans and machines. It will not be difficult to integrate and have a separate table generated automatically.

**Comment by mirceaulinic** [comment]
Ok cool - in that case I don't have any further questions here :)
