### ISSUE TITLE
RegEx validate not working

### ISSUE THREAD

**Issue by XioNoX** [napalm-automation/napalm-base#201]
From https://github.com/napalm-automation/napalm-base/pull/176

I tried to use:
```
- get_lldp_neighbors:
    ge-1/0/2:
      - hostname: fw1\[a|b\].private.lon2
        port: "ethernet1/13"
```
With different variations of hostnames:
`fw1[a|b].private.lon2`, `fw1[ab].private.lon2`, `fw1\[ab\].private.lon2`
And with and without quotes, with no luck.

The result is always:
```
        "compliance_report": {
            "complies": false, 
            "get_lldp_neighbors": {
                "complies": false, 
                "extra": [], 
                "missing": [], 
                "present": {
                    "ge-1/0/2": {
                        "actual_value": [
                            {
                                "hostname": "fw1b.private.lon2", 
                                "port": "ethernet1/13"
                            }
                        ], 
                        "complies": false, 
                        "nested": false
                    }, 
                    "ge-1/0/3": {
                        "complies": true, 
                        "nested": false
                    }
                }
            }, 
```

**Comment by XioNoX** [comment]
@dbarrosop @mirceaulinic 
Digging a bit, more, it doesn't reach [line 124](https://github.com/napalm-automation/napalm-base/blob/master/napalm_base/validate.py#L124) as it tries to compare a list of dicts, instead of going deeper and comparing the actual values.
Printing `src` and `dst` from [line 127](https://github.com/napalm-automation/napalm-base/blob/master/napalm_base/validate.py#L127) shows:
```
[{'hostname': 'fw1[ab].private.lon2', 'port': 'ethernet1/13'}]
[{'hostname': u'fw1b.private.lon2', 'port': u'ethernet1/13'}]
```
Maybe it's a long shot with unknown complications, but modifying the following starting from [line 122](https://github.com/napalm-automation/napalm-base/blob/master/napalm_base/validate.py#L122)
```
    else:
        if isinstance(src, py23_compat.string_types):
            m = re.search(src, py23_compat.text_type(dst))
            return m is not None
        elif(type(src) == type(dst) == list):
            pairs = zip(src, dst)
            diff_lists = [[(k, x[k], y[k]) for k in x if not re.search(x[k], y[k])] for x, y in pairs if x != y]
            return empty_tree(diff_lists)
        else:
            return src == dst

def empty_tree(input_list):
    """Recursively iterate through values in nested lists."""
    for item in input_list:
        if not isinstance(item, list) or not empty_tree(item):
             return False
    return True
```
Inspired by: 
http://stackoverflow.com/questions/9845369/comparing-2-lists-consisting-of-dictionaries-with-unique-keys-in-python
and
http://stackoverflow.com/questions/1593564/python-how-to-check-if-a-nested-list-is-essentially-empty

I tested it with all my validation files, on PaloAlto and Juniper (using get_route_to, traceroute and get_lldp), directly via python and through Ansible with no issues.

If you think there is no issues with doing it that way, I'll send a PR right away.

**Comment by dbarrosop** [comment]
Mmm, problem here is that there is no list of dictionaries. Are you using some modified version? Like the one proposed on #202?

**Comment by XioNoX** [comment]
That list of dict is different from #202, here it's the list of neighbors returned for a specific interface.

**Comment by dbarrosop** [comment]
Ok, I see what you mean. This threw me off:

```
- get_lldp_neighbors:
    ge-1/0/2:
      - hostname: fw1\[a|b\].private.lon2
        port: "ethernet1/13"
```

Feel free to open a PR but add some test case so we can see it works, please.

**Comment by XioNoX** [comment]
Opened PR https://github.com/napalm-automation/napalm-base/pull/203
