### ISSUE TITLE
Document recommended install procedure

### ISSUE THREAD

**Issue by ktbyers** [napalm-automation/napalm-base#25]
Given the new split up repositories, the install procedure for NAPALM is not self-evident.

We need to document:

1. Install procedure using pip
2. Install procedure using python setup.py install

Probably cover any differences if installing full NAPALM versus only support for specific platform (i.e EOS/JUNOS/IOS)

**Comment by ktbyers** [comment]
I would assign this issue to me...but looks like I can't.

**Comment by dbarrosop** [comment]
Looks like there is another issue tracking this napalm-automation/napalm#284
