### ISSUE TITLE
Extending napalm with SSH proxy support.

### ISSUE THREAD

**Issue by zhecho** [napalm-automation/napalm-base#265]
Using napalm via ssh proxy. Suppose that we want to use napalm but we have jump station (for security/other reasons) with ssh server on it before accessing network devices.

Do you think that the following ssh_config_proxy is ok?  or we need to implement some other way to do this? (note: ssh-agent should be up and running with loaded key for the jump station in order to use this config file)

Host ip.addre.ss
HostName ip.addre..
User username
Port 22
StrictHostKeyChecking no
ProxyCommand ssh username@hopping.station.com nc %h %p

(netcat / ssh / telnet can be used as the ProxyCommand option) 

I've managed to use this with netmiko  module and ssh_config_file and it works only for ssh (telnet is not supported )  

Best Regards!

**Comment by ktbyers** [comment]
@zhecho This should already exist for Netmiko-based SSH NAPALM drivers.

You will need to use optional_args dictionary to provide all of the additional Netmiko arguments. In other words:

```
optional_args = {}
optional_args['key1'] = 'value1'
```

Where all the key/values you specify are the additional needed Netmiko arguments.

Let me know if this doesn't work.
