### ISSUE TITLE
Travis test times

### ISSUE THREAD

**Issue by ogenstad** [napalm-automation/napalm-base#283]
I was looking at the Travis builds yesterday and thought that it took quite some time. A lot of time was spent just to prepare the environment.

A thought I had was to look at all of the required libraries which needs to be compiled in order to be installed. Some of them can probably be installed as pre-compiled binaries with apt-get. And then build the virtualenvs to include site-packages. Not really if that would work with Tox (which isn't used from napalm-base at the moment), otherwise it could perhaps be possible to solve the problem with different Python versions using their own Docker containers.

The downside of doing this would be that the tests wouldn't react if someone made the wrong changes to some requirements.txt file. Also if it works with Tox I imagine there could be scenarios when testing locally where it picks an old package from the site-packages instead of using a new fresh one.

Would this be something useful to try or is it better to just leave it as it is?

**Comment by ktbyers** [comment]
This hasn't been important to me (i.e. from my perspective they run fast enough).

**Comment by bewing** [comment]
I think one of the most important parts of tox is that it actually checks that the package installs cleanly, and then passes tests.  Bypassing requirements.txt defeats this.  While I won't argue in the future a "quick" testsuite might not have a purpose, I would still want full tox testing on release merges.

**Comment by dbarrosop** [comment]
I agree with bewing. Travis should be a clean env and as generic as possible. At the end of the day, you should push your code after testing locally and ensuring everything is working fine ;)

I am closing this issue as I don't think we should fix it. I wouldn't mind revisiting the testing suite though after the merge.
