### ISSUE TITLE
Barracuda API extension

### ISSUE THREAD

**Issue by BullfroG21** [napalm-automation/napalm-base#286]
Hi,

Are there any future plans of implementing a feature for the Barracuda API.

with kind regards

**Comment by ktbyers** [comment]
@BullfroG21 Additional NAPALM drivers are driven by individuals who want to add support for that platform. 

So if you want this for Barracuda, you would probably need to add it.

There are also some requirements that the platform would have to meet (as we try to maintain a fairly consistent NAPALM interface).

**Comment by dbarrosop** [comment]
Regarding the requirements, we will try to post something in the near future as we don't have them yet "formalized".

Is this driver something you will working on?

**Comment by dbarrosop** [comment]
Closing, feel free to keep the discussion going though.
