### ISSUE TITLE
Design suggestion: use class for returned data structures instead of dict

### ISSUE THREAD

**Issue by jzohrab** [napalm-automation/napalm-base#39]
Currently the code builds raw dictionaries for the various methods.  The tests check that the dictionaries match napalm_base.test.models structures.

Since the returned data structure is important, these test-only models could be "promoted" to fully-fledged classes of the design domain.  The driver methods could then populate these data structs, and the structs could have a `validate` method to ensure the data adheres to a required standard.  This would be good for program documentation and correctness.

May or may not be useful at this point, given that many methods have been implemented.

**Comment by jzohrab** [comment]
I'm working on a Nexus method right now, and may use this idea during implementation.  It could perhaps be generalized if the team felt it useful.

**Comment by dbarrosop** [comment]
It's not a bad idea, the only problem is that we will still have to pretend we are a dictionary to avoid breaking the API. The good thing is that our use case is so simple we should be able to implement a base class to implement everything we need and just have to define attributes and validators.

Feel free to propose something for nexus, I might end up refactoring some of your stuff into a base class so we can reuse stuff.

By the way, note that whatever we build has to be backwards compatible. So if something is accessed today `bgp_neighbors['something`]['whatever']` that should still work with the class.

**Comment by dbarrosop** [comment]
Mmmm, my brain is working too fast right now... More than it should be. Another thing we could do instead is leave things as they are and start adding new methods that adhere to OC standard. Then we could use `pyangbing` to do the validation and get the classes. This would be a new set of methods, in addition of `get_bgp_neighbors` we would have `get_oc_bgp_neighbors`.

**Comment by dbarrosop** [comment]
@mirceaulinic thoughts?

**Comment by mirceaulinic** [comment]
@jzohrab I see your point and the gain by doing this. Although the tests are pretty fast and they just check if some keys are present and having the correct datatype, would not be overkill to check each and every output?
I do see the benefit of making sure that the output has the exact structure as expected. That makes sense. But I'm just wondering: have you ever seen a different output than designed? (don't claim it's not possible).

And what would happen if say a field has wrong datatype? (e.g. array with valid str entries instead of int)

**Comment by dbarrosop** [comment]
I am inclined towards @mirceaulinic line of thought, I do see the value but is it worth the effort? I would rather focus on making new methods that are OC compliant and maybe some day deprecate methods that no longer make sense. If we have a `get_oc_bgp_neighbor` we *probably* don't need a `get_bgp_neighbor`. Some will hardly die, let `get_users` or `get_ntp_peers` but those are simpler methods.

**Comment by jzohrab** [comment]
It may well not be worth the effort at this point, given the existing amount of implementation that's complete.  For future stuff it may be something to keep in mind.

The existing unit tests check data structure, but don't check actual data mapping.  In my Nexus test, I'll add some extra checks showing what I mean.  It may look like overkill, but it's my preferred way of testing/working and you can see if it's useful or not.

The reason I bring it up at all is that recently we've found some inconsistencies in the returned data (eg the get_interfaces_ip in eos), and I figured that formalizing the classes would safeguard everyone for refactoring and fixes.  Also when I started implementing a nexus method it wasn't clear what was needed.  Part of this may be onboarding too :-)

So, I'll do something for my Nexus work, and everyone can judge if it's something worth doing.  It's not needed to do a big bang fix for everything, and it honestly may have little to no payoff.  But let's see how it goes.  Thanks @dbarrosop and @mirceaulinic for your consideration.

**Comment by mirceaulinic** [comment]
Sure, I would like to see an working example. Take your time and let us know when you have something available! Thanks for the idea & looking forward for your work!

**Comment by mirceaulinic** [comment]
> Also when I started implementing a nexus method it wasn't clear what was needed. Part of this may be onboarding too :-)
> 
Could you please point out what was the issue here? Missing documentation for developers perhaps?

**Comment by jzohrab** [comment]
Re not clear what was needed - I wasn't sure what the data structure was for get_bgp_neighbors.  I eventually read through the source in napalm_base's base.py, found it was using a model for verification, and found the model in napalm_base/test/models.py.  The test code in the nsox driver didn't say anything about expected return values, given inputs.  Eventually I ran through a test in another driver that had this method implemented, found the napalm_base installed in the nested virtualenv folder, and added some print statements to see what was actually coming back.  So it took a while to find what was needed.

If there are docs anywhere, I didn't see them. Could be just me.

**Comment by mirceaulinic** [comment]
You mean the [output structure](http://napalm.readthedocs.io/en/latest/base.html#napalm_base.base.NetworkDriver.get_bgp_neighbors) was unclear?

**Comment by mirceaulinic** [comment]
I find it pretty clear, also in terms of input params (see [get_bgp_config](http://napalm.readthedocs.io/en/latest/base.html#napalm_base.base.NetworkDriver.get_bgp_config) where the input params are very briefly described too). Definitely we may improve it if not obvious enough for devs.

**Comment by dbarrosop** [comment]
Yeah, the structure is defined in napalm-base. Whats not clear? What would
you suggest changing? It should be even documented in RTD.

**Comment by jzohrab** [comment]
Well, I feel like a dork. :-P  Don't judge me @mirceaulinic and @dbarrosop !  :-)

**Comment by mirceaulinic** [comment]
That's fine, can happen.
Can share your experience, why haven't you found the right doc -- not obvious where to look, not emphasised enough? If you had this problem, others might have it too. Probably we should include somewhere a note to point exactly to the resources for devs.

**Comment by jzohrab** [comment]
Probably a link on the main readme, taking devs to a simple page like the following:

- here is how you build the project
- here is how you run the tests locally
- here is the 50,000-foot architectural overview (i.e. a few paragraphs/diagrams describing major classes and interfaces etc) - not too deep, just enough docs
- here are the docs for the methods
- here are our style guidelines and testing guidelines

**Comment by dbarrosop** [comment]
@jzohrab don't worry, we weren't trying to nail you, just looking how to improve it. I agree with you that we are lacking some instructions, we are still waiting for Matt to finish their proposal so we can see how to document things best, his proposal might change how some things are done today so no point on documenting yet... What about the skeleton? Do you think that covers some of the topics you mention? https://github.com/napalm-automation/napalm-skeleton

**Comment by jzohrab** [comment]
Let's see what Matt delivers, and then I can contribute some initial dev docs that we can iterate on.

**Comment by dbarrosop** [comment]
Regarding the main topic, using classes instead of dicts. With the OC effort going on I think this is not relevant anymore. Feel free to open new issues if you think there is something else we should discuss,
