### ISSUE TITLE
textfsm_extractor converts all entries to string

### ISSUE THREAD

**Issue by inetuid** [napalm-automation/napalm-base#44]
At line 117 of napalm_base/helpers.py the following code converts everything to a string:

`entry[fsm_handler.header[index].lower()] = str(entry_value)`

This includes lists that can be returned from the template. I suggest it changes to the following:

`entry[fsm_handler.header[index].lower()] = entry_value`

Matt.

**Comment by mirceaulinic** [comment]
I not not recall why it is string. Most probably I had some reasons, but I can't remember this particular detail.
What driver are you using? I would need you to confirm a detail.

**Comment by inetuid** [comment]
It's not a 'standard' driver - I'm working on a generic Linux driver (with the idea of layering Cumulus on top) and I'm just making use of the helper in 'base'.

If I can help by confirming the detail please let me know.

**Comment by mirceaulinic** [comment]
Very interesting!
As I said earlier, I am sure I had something in mind by doing so, but I don't know what. Looking at the implementation, indeed it does not look right to restrict the datatype.

If you can provide any example of input + template would be great. Also a PR would be also appreciated and I will test all napalm drivers that make use of this helper.

**Comment by inetuid** [comment]
See #45

**Comment by mirceaulinic** [comment]
This issue can be closed now.
