### ISSUE TITLE
Cumulus Linux driver / Linux base driver thoughts

### ISSUE THREAD

**Issue by inetuid** [napalm-automation/napalm-base#46]
I've been thinking about how to approach writing a driver for Cumulus Linux. This is a bit of a brain dump of where I am at present...

The getters() are relatively trivial as it's just a matter of parsing the relevant Linux commands. This made me think the best option maybe to start with a base Linux driver that any Linux based NOS could inherit from just adding any specifics on top.

The configuration side is more tricky as there is no one place where all the configuration is stored. You need to set multiple things in different files (or using different commands) with differing syntax. Cumulus provide a list of files (for backup) that may be touched during configuration which provides a starting place of where to look in terms of managing this - https://docs.cumulusnetworks.com/display/DOCS/Upgrading+Cumulus+Linux#UpgradingCumulusLinux-UnderstandingtheLocationsofConfigurationDataforManagement,Migration,andBackup

Cumulus also have some Ansible code that has some support for interfaces, VLANs and routing (Quagga) which might be used to assist with the configuration side - https://github.com/CumulusNetworks/cumulus-linux-ansible-modules

Another approach I'm considering is writing an interface that hides all this - something like the approach taken by Mikrotik with their Routerboard OS (ROS). Basically its just a translation from the CLI to/from the underlying configuration files or commands. Might be somewhat limiting however to only support what the CLI provides rather than the full range of commands available.

**Comment by dbarrosop** [comment]
> the best option maybe to start with a base Linux driver that any Linux based NOS could inherit from just adding any specifics on top

Agree. Even easier than that, we could just have a Linux driver with some defaults (quagga for routing, for example) and use the "optional_args" in case someone wants to change it to bird or some other.

Regarding the configuration bits. The idea I had is to wrap on a json file what we want to do. For example:

https://gist.github.com/dbarrosop/bfe6dd28cf68a2f5c38afe05456c0d69

- `service` is the name of the service.
- 'action_on_change` would be if we want to reload or restart the service after a change. Might be that we don't want to do anything.
- `conf_files` is a list of configuration files that can be of type "configuration" or "script.

What do you think? This would give us flexibility without adding too much complexity I think.

**Comment by inetuid** [comment]
I think it could work. I'm a bit reticent on just using configuration to change behaviour (even though this is the vogue in software development at present) as it works when the actions can be directly mapped but is challenging where you actually need to run some code as well. You could pass a callback to do the work but then that's not much different to subclassing it. I'm struggling with issues related to this in the napalm-snmp driver when the MIBs aren't a direct mapping and even with translation tables you still can't always neatly map across.

That said, the way Linux uses the CLI and flat configuration files this probably won't be as much of a problem.

**Comment by haderp** [comment]
I don't know if this is still on the radar, but Cumulus has added a command line utility with 3.2.0 that solves most of the issues discussed here.

**Comment by dbarrosop** [comment]
Yeah, I think that's a great addition and we should be able to add a driver for cumulus based on that CLI. Any volunteers? ;)

**Comment by GGabriele** [comment]
I'm tempted :) unless @haderp does have a plan to work on it.

**Comment by haderp** [comment]
@ggabriele I have no plan, but I'd like to help. Full disclosure, I'm an network engineer, not a programmer, and I will definitely have questions and need guidance, but I can contribute on the bulk of the driver.

**Comment by GGabriele** [comment]
@haderp working on a driver from scratch is a great way to improve your development skill! :)

**Comment by haderp** [comment]
@GGabriele There's no way I can do it on my own, but if you want to take the lead on it, and divvy out the work, I am onboard.

**Comment by itdependsnetworks** [comment]
If I may interject here. @haderp It can be helpful if you can take the primary methods and describe how they are done via CLI with examples. 

e.g.
Config. replace
Config. merge
Compare config
Atomic Changes
Rollback

Once those are known, it will be a bit easier to program it.

**Comment by dbarrosop** [comment]
Yeah, I think it would be great if @GGabriele could bootstrap the driver as there are some considerations around napalm and then the rest is just a matter of translating CLI commands into python : ) @haderp if you know how that CLI works your help will be surely appreciated even if you don't know python. You can always help out describing how to implement the methods as @itdependsnetworks  mentioned and testing. And if you want to practice your python, don't shy away, we are all friendly people and PRs are a great learning tool.

**Comment by haderp** [comment]
I can get the commands, expected output, and start translating some of them. 
I am new to github. What's the proper way to post it all?

**Comment by dbarrosop** [comment]
Wait until @GGabriele bootstraps the driver (if he finally volunteers ;) ). Then the best way is probably creating issues (one per method) on the driver's repo and then adding as much info there as possible and/or sending a PR for method.

**Comment by GGabriele** [comment]
@haderp @dbarrosop let's do that :)

@haderp are you on Slack?

**Comment by haderp** [comment]
@GGabriele I am.

**Comment by jmrenshaw** [comment]
I'm interested in helping out as well, similarly to @haderp I am far from a proficient coder but happy to start with adding info to the issues and go from there.

**Comment by dbarrosop** [comment]
The napalm-automation/napalm-cumulus has been created. Let's take any discussion there from now on. Feel free to comment/open issues. People testing, coding (code doesn't have to be super pretty and PRs are a great way of learning) or just helping with the necessary commands to implement certain methods are welcome :)
