### ISSUE TITLE
advertise_prefix_count or advertised_prefix_count in get_bgp_neighbor_detail()

### ISSUE THREAD

**Issue by inetuid** [napalm-automation/napalm-base#50]
The napalm_base/test/models.py uses advertise_prefix_count whereas the documentation (http://napalm.readthedocs.io/en/latest/base.html) uses both. It would seem more natural for it to be advertised_prefix_count to match received/accepted/suppressed etc but it would be good to confirm which it is.

**Comment by mirceaulinic** [comment]
It's a typo indeed, the value is ```advertised_prefix_count```.
