### ISSUE TITLE
get_mac_address_table() and 'bridge domains'

### ISSUE THREAD

**Issue by inetuid** [napalm-automation/napalm-base#52]
I'd like to start a discussion on whether get_mac_address_table() should be extended to support bridge domains rather than the current single table (albeit with VLANs). This would be analogous to VRFs for IP routing related functions.

My proposal would be for the outer dictionary key to be the bridge domain and the inner list would be the same (or similar) to the current output. Something like

```
{
  'bridge-domain1': [
    {
      'mac': <MAC>,
      'interface': <IF_NAME>,
      'vlan': <VLAN_ID>,
     etc...
    },
   {
     As above...
   },
  ],
  'bridge-domain2': [
   As above...
  ]
}

```

How VLAN fits into this I'm not sure as each bridge domain could be VLAN aware (or not). I guess a VLAN is a bridge domain so it may just need to move up a level.

Matt.

**Comment by mirceaulinic** [comment]
Hi @inetuid - would be nice to have a method doing that. But not the current ```get_mac_address_table```, a different one.
I will give you an example: in the past we had only```get_lldp_neighbors```; later we added ```get_lldp_neighbors_detail``` which is just a more complete version, let's say. Basically the difference is tiny between them. But we decided to keep both to not broke the existing behaviour. Same here.
For ```get_bgp_neighbors_detail``` we made an exception - it was a design mistake, not a desired action to not have the VRF key and it did not make sense to add something weird like ```get_bgp_neighbors_detail_with_vrf```. So we had to consider this drastic decision and fix the drawback.
Please feel free to submit a proposal for a new method.

**Comment by inetuid** [comment]
If my device doesn't nicely support get_mac_address_table() but did support get_bridge_domain_mac_table()* would it be reasonable to return NotImplementedError for the former to avoid returning partial or incorrect information?


Matt.

* Not necessarily my proposed name.

**Comment by mirceaulinic** [comment]
Absolutely, not all the drivers need to implement ```get_mac_address_table``` (e.g. IBM or FortiOS do not implement it).
```get_bridge_domain_mac_table``` sounds OK for me.

**Comment by dbarrosop** [comment]
Is there an OpenConfig model for that? Any new method we implement should follow the OC model if it exists.

**Comment by inetuid** [comment]
In terms of naming, the 'standard' seems to be MAC learning table, forwarding database, or just FDB - name should probably reflect one of these.

**Comment by inetuid** [comment]
Had a look and OC seem to have a L2VSI network type but no corresponding model for what it should contain.

**Comment by dbarrosop** [comment]
I am going to see if I can bring this to the people behind OC and see if this is something we can define and then implement.

**Comment by inetuid** [comment]
Don't think this ever reached a final conclusion. Should a raise a PR for this new method or does it depend on the outcome of the OpenConfig work as per #53?

**Comment by dbarrosop** [comment]
This somehow got forgotten, I have created an issue to keep track of it openconfig/public#30

**Comment by mirceaulinic** [comment]
@inetuid for the moment we could introduce the following API change: the method `get_arp_table` to accept an argument `bridge_domain`. While this is not going to solve the problem, it allows the user switch between domains.
Please let me know if that suits your needs!

**Comment by dbarrosop** [comment]
The OC people fixed it on their end a few months ago:

https://github.com/openconfig/public/commit/15b0137f7261515f6527bdd443bee4ad9f9cf63f

Maybe we can close this one and use the OC framework?

**Comment by mirceaulinic** [comment]
Perfect, let's do this then!

**Comment by dbarrosop** [comment]
I will close it then, sorry this is going so slow : (

**Comment by dbarrosop** [comment]
Btw, feel free to open an issue on the `napalm-yang` if this is something you are still interested in.
