### ISSUE TITLE
Generic 'instance' awareness

### ISSUE THREAD

**Issue by inetuid** [napalm-automation/napalm-base#53]
There have been some recent discussion about supporting VRFs in get_bgp_neighbors_detail() and bridge domains in get_mac_address_table() but these are not the only methods where there is potential missing support for some form of instance (routing, bridge etc).

I suggest that get_arp_table(), get_interfaces_ip(), get_route_to(), ping() and traceroute() should also be instance aware (or other methods added that are instance aware). It may be that lldp, ntp and probes also need to be on the list.

Thoughts?

Matt.

**Comment by dbarrosop** [comment]
Those are probably too much changes and I don't want to break the API so three things:

1. Worst case, for most methods we can have a vrf/instance argument and return data for that vrf/instance. That will give you instance awareness without breaking the API. We will have to document which method/drivers support this though, which might be boring and tedious but doable.
2. New methods that just wrap around the existing ones. Might be better from a documentation perspective but maybe worst from an implementation point of view??? I think I would rather not do this one...
3. Try to move towards the OC model. This is the hardest but probably the one that will pay off more.

What do you think of these potential solutions?

**Comment by inetuid** [comment]
Assuming that the OC model delivers something usable in a reasonable timescale, I'd also say this has the best future proofing. Other than being aware of it, I've not really followed progress on OC - is it likely to deliver something any time soon?

Otherwise, the option to pass in a VRF/instance to existing methods would fill the requirement. It would need some way of enumerating the VRFs/instances as well to go with it I think.


Matt.

**Comment by dbarrosop** [comment]
Quick update; the OC team is working on this. There is already a proposal but due to holidays the approval is being slower than usual.

**Comment by dbarrosop** [comment]
If you don't mind I am going to close this issue. I think it makes complete sense but we can't break the API by doing those changes on existing methods. So I would suggest start working on the OC models and implement what you suggest as we move forward. Feel free to reopen this issue if you think it needs further discussion.

**Comment by inetuid** [comment]
Agreed that extending a number of existing methods is not good. Let's close and see where the OC methods/model takes us.
