### ISSUE TITLE
Method to retrieve light levels from optics installed

### ISSUE THREAD

**Issue by narJH27** [napalm-automation/napalm-base#56]
This is a feature request. 

It would be nice to have a method implemented across the various vendor drivers, such that light levels, ie, tx power and rx power, can be retrieved from the optics attached to the ports on the switch.

Is this something that is on the roadmap for napalm?

**Comment by mirceaulinic** [comment]
I think I've seen this request a couple of months ago - don't remember exactly where.

It would be interesting indeed, but I don't have it on my roadmap.

Do you have any output structure in mind? You can open a PR to discuss if interested.

**Comment by narJH27** [comment]
I am working on modeling this. I will open a PR to discuss it once I have something tangiable to show for.

**Comment by dbarrosop** [comment]
There was a proposal long ago but it led nowhere. Here it is in case it's useful:

napalm-automation/napalm#139

However, moving forward new getters should comply with the OC model unless there is no model. In this particular case this seems like a good candidate:

https://github.com/openconfig/public/blob/master/release/models/platform/openconfig-platform-transceiver.yang

As this is completely knew, I can probably try to help defining our model and maybe mocking something.

**Comment by mirceaulinic** [comment]
<img width="776" alt="screen shot 2016-07-13 at 11 03 40" src="https://cloud.githubusercontent.com/assets/16694679/16799586/853b17f4-48e9-11e6-8a98-82881f472899.png">
That's helpful 😄

**Comment by dbarrosop** [comment]
It was just for reference, we should use the OC model anyway.

**Comment by mirceaulinic** [comment]
Sure, I was just trolling the previous "proposal"

**Comment by narJH27** [comment]
@dbarrosop Sure David! It would be great if you could define a model based off of OC and we can discuss that before any code is written around it.

**Comment by dbarrosop** [comment]
The model part should be easy, the tricky part is going to be adding the OC framework in napalm-base. But I will try to get something mocked over the weekend so you can work on the parsing side while I put the OC framework together.

**Comment by narJH27** [comment]
sounds like a plan!

**Comment by dbarrosop** [comment]
I am still trying to figure out what's the best way to do this. However, the `dict` that your object will have to return will be something like this:

```
{
   			"openconfig-platform:components": {
	    		"component": [
	    			{
	    				'name': 'et1',
	    				'transceiver': {
	    					'physical_channels': {
	    						'channel': [
	    							{
	    								'index': 0,
	    								'state': {
	    									'input_power': {
	    										'instant': 0,
	    										'avg': 0,
	    										'min': 0,
	    										'max': 0,
	    									},
	    									'output_power': {
	    										'instant': 0,
	    										'avg': 0,
	    										'min': 0,
	    										'max': 0,
	    									},
	    									'laser_bias_current': {
	    										'instant': 0,
	    										'avg': 0,
	    										'min': 0,
	    										'max': 0,
	    									},
	    								}
	    							}
	    						]
	    					}
	    				}
	    			}
	    		]
	    	}
	    }
```

There is an explanation of the attributes here:

https://github.com/openconfig/public/blob/master/release/models/platform/openconfig-platform-transceiver.yang

**Comment by narJH27** [comment]
@dbarrosop Thanks for putting that together! 

I am still curious as to whether the vendors support such granular information from the transceivers, ie, instant power, avg power, min/max power? The only info I have been able to find using cli commands on the vendor boxes thus far, is tx and rx power in Watts. Can you please help understand your thoughts behind the same?

**Comment by dbarrosop** [comment]
The idea is that the models should work with any network device, that includes optical switches so those will most surely give more information. Nobody expect to have all the values on all the devices. For example, you can find this note on the definition:

> If avg/min/max statistics are not supported, the target is expected to just supply the instant value";

A benefit of using OC vs building our own is that a lot of people is thinking how to structure those models so I guess the result will be less biased than if we would design our own model which would probably fix our current use case : ) Another benefit is that at some point this might be an industry standard so we might be able to get these from the devices directly without any sort of parsing.

**Comment by narJH27** [comment]
Oh I completely understand the intent behind Openconfig and its applicability in the industry moving forward. Was curious to know your thoughts on the values that are not readily available from the vendors themselves. Thanks for clarifying that!

**Comment by narJH27** [comment]
@dbarrosop I was looking at the proposed data model for this again, and was wondering what the 'physical_channels' and 'channel' values for a regular SFP port on a IOS/IOSXR, Junos or Arista Switch would be?

**Comment by dbarrosop** [comment]
rule of thumb; if you have no idea what means use 0 as that's the default : )

**Comment by narJH27** [comment]
Created a PR #58

**Comment by dbarrosop** [comment]
Closing this one : )
