### ISSUE TITLE
Document load_template

### ISSUE THREAD

**Issue by dbarrosop** [napalm-automation/napalm-base#6]

**Comment by mirceaulinic** [comment]
I was thinking that we could add one extra param: ```eternal_template``` and let the users pass an absolute path to a non-standardized template.  What do you think, @dbarrosop?

**Comment by dbarrosop** [comment]
I think that you were reading my mind. Was planning to suggest that as well :)

How do you envision this though? Given the name you gave to the variable I think we were thinking in two different implementations. The way I thought about this was as follows:

1. I have my own folder `PATH` where I put all my templates.
2. Each driver has it's own subfolder, ie, `PATH/eos`, `PATH/junos`, etc...
3. When I want to use my own template I just do `d.load_template('my_service', template_path=PATH)`

So my code doesn't have to figure out the current driver or anything. Is this what you were thinking?

**Comment by mirceaulinic** [comment]
Yes, exactly! I don't have a schedule it right now, but will make some time probably next week and implement it.

**Comment by mirceaulinic** [comment]
@dbarrosop I think this one can be closed by now
