### ISSUE TITLE
Increment napalm package version for each release

### ISSUE THREAD

**Issue by natm** [napalm-automation/napalm-base#64]
We have experienced service deployment issues when new napalm packages are released, but the package version number is not incremented.

I would like to pin our deployments to a particular napalm release until we have tested it, but with large changes being included without the version be incremented this is problematic.

An example of this is where napalm-panos was added as a package dependency to the base package, but the base version not changed. The panos module itself included extra Python dependencies which needed additional system packages installed.

**Comment by dbarrosop** [comment]
Could you elaborate on the issue, please? I am not sure I understand the issue you describe, `pip` doesn't allow you to publish new code without increasing the release and as you can see [here](https://github.com/napalm-automation/napalm-base/releases) each release has a different version. The same applies for the rest of the drivers.

And here is the release that added `panos` to the "all-in-one" installer:

https://github.com/napalm-automation/napalm/releases/tag/1.1.0

And it works as expected:

```
$ pip install "napalm<1.1.0"
...
Successfully installed MarkupSafe-0.23 PyYAML-3.12 bitarray-0.8.1 bnclient-0.3 cffi-1.8.2 cryptography-1.5 enum34-1.1.6 gtextfsm-0.2.1 idna-2.1 ipaddress-1.0.16 jinja2-2.8 junos-eznc-2.0.0 lxml-3.6.4 napalm-1.0.2 napalm-base-0.15.0 napalm-eos-0.2.1 napalm-fortios-0.1.1 napalm-ibm-0.1.1 napalm-ios-0.1.7 napalm-iosxr-0.2.2 napalm-junos-0.2.1 napalm-nxos-0.2.1 napalm-pluribus-0.2.0 ncclient-0.5.2 netaddr-0.7.18 netmiko-0.5.6 paramiko-2.0.2 pyFG-0.47 pyIOSXR-0.21 pyPluribus-0.3.0 pyang-1.7 pyangbind-0.5.8 pyasn1-0.1.9 pycparser-2.14 pycsco-0.3.5 pyeapi-0.6.1 pyserial-3.1.1 scp-0.10.2 six-1.10.0 xmltodict-0.10.2
```

No trace of `panos`.

And `napalm-panos` is not a dependency of `napalm-base`. It's a dependency of `napalm` as that is the "all-in-one" installer.

Please, let me know if I am missing something.

**Comment by dbarrosop** [comment]
I am going to close this one. Feel free to reopen if you think this is unanswered.
