### ISSUE TITLE
add get_config()

### ISSUE THREAD

**Issue by dbarrosop** [napalm-automation/napalm-base#65]
Original ticket napalm-automation/napalm#291 created by @grizz
### Add a function to get the full config as a text blob

Would obviously be platform specific, but would be handy for using NAPALM for development and device changes.

**Comment by dbarrosop** [comment]
The description of the method can be found here:

https://github.com/napalm-automation/napalm-base/pull/69/files

Thoughts?

**Comment by dbarrosop** [comment]
@grizz let me know if this proposal looks good to you.

**Comment by grizz** [comment]
Looks good, thanks for stubbing it in. I wonder if it would be better to pass a flag to determine which configs to get since it can take a while on some platforms?

**Comment by mirceaulinic** [comment]
This has been implemented on all drivers, except IBM - which we consider deprecated.
So this is fixed IMO.
