### ISSUE TITLE
Operational validation method(s)? #hackathon2016

### ISSUE THREAD

**Issue by GGabriele** [napalm-automation/napalm-base#83]
I was wondering if it may make sense to have some operational validation capabilities into NAPALM, like having the possibility to run `device.validate("bgp")` and check if everything looks as expected.

If it's cool, what do you think may be something _good_ to validate? BGP peers, reachability, LLDP peers..?

**Comment by ktbyers** [comment]
@GGabriele I think it could be interesting to make this more general. By this I mean have a 'command' you can run and a ruleset you can run the output of the command against to say whether it validates or not.

I did this where it was validating the running-config and the ruleset had a pretty simple engine that stated whether something had to be in the config or could not be in the config.

**Comment by dbarrosop** [comment]
Could you show an example on how it would work? I am not sure if I understand what you mean. Just fake everything, pretend the code is there, and show how it would work on the console ; )

**Comment by GGabriele** [comment]
@dbarrosop my original idea was to support the validation of a set of features. Let's imagine you want to validate BGP peers, `validate()` would search for a source of truth (YAML file?), load the expected BGP peers status and check if there is a match with `get_bgp_neighbors` result.

But I like what @ktbyers proposed and I'm trying to think about it.

**Comment by ktbyers** [comment]
Just thinking out loud here...

validate_getters = ['get_config']                  # will validate what is returned by get_ operation
validate_files = {
    'get_config': 'get_config_validation.yml'
}

#### example rules in .yml file #####
config_requires:           # items the config must have
    - enable secret *
    - service password-encryption

interface_set:           # define sets of interfaces for what they require / are missing

config_missing:          # items the config can't have
   - enable password *


You could expand this to be any NAPALM getter method (not just the config)

.validate()                  # either pass or fail and shows you in clear way everything that fails and why they fail.

**Comment by ktbyers** [comment]
Basically, would be the equivalent of unit tests for configuration and the values returned by NAPALM getters.

**Comment by GGabriele** [comment]
Exactly. I was first thinking it as more related to getters, but it will definitely be useful for configuration too.
Thanks for your hints @ktbyers !

**Comment by dbarrosop** [comment]
Ok, makes sense. Cool thing about that is that if it's generic enough it can either be part of napalm-base or even live completely outside of napalm. Anyway, feel free to mock it and let's see how it ends up looking : )

**Comment by GGabriele** [comment]
So far I have this for getters (tested with NXOS):

Sample `validate.yml` file:
```
---

get_interfaces:
  Ethernet2/5:
    is_enabled: true
    is_up: false

  loopback103:
    is_enabled: false
    is_up: false

  Vlan100:
    is_enabled: false
    is_up: false

get_facts:
  os_version: 7.0(3)I2(2d)
  interface_list:
    - Vlan5
    - Vlan100
  hostname: n9k2

get_lldp_neighbors:
  mgmt0:
    - hostname: PERIMETER
      port: Fa1/0/11
```

Sample CLI workflow:
```
>>>import json
>>>from napalm import get_network_driver
>>>driver = get_network_driver('nxos')
>>>device = driver('nxos', 'ntc', 'ntc123')
>>>device.open()
>>>
>>>getters = ['get_interfaces', 'get_facts', 'get_lldp_neighbors']
>>>validation = device.validate(getters=getters)
>>>
>>>print json.dumps(validation, indent=4)
```

Sample results:
```
{
    "get_interfaces": {
        "Vlan100": [
            "Expected 'is_enabled: False', found 'is_enabled: True' instead"
        ], 
        "loopback103": [
            "Expected 'is_enabled: False', found 'is_enabled: True' instead", 
            "Expected 'is_up: False', found 'is_up: True' instead"
        ]
    }, 
    "get_lldp_neighbors": {
        "mgmt0": [
            "Expected but not found: {'hostname': 'PERIMETER', 'port': 'Fa1/0/11'}"
        ]
    }, 
    "get_facts": {
        "os_version": [
            "Expected 'os_version: 7.0(3)I2(2d)', found 'os_version: 7.0(3)I4(1)' instead"
        ], 
        "interface_list": [
            "Expected but not found: Vlan5"
        ]
    }
}
```

It will print `Expected but not found: X` if the dict value is a list, while it will print something like `Expected 'X', found 'Y' instead` if the dict value is a dict/unicode/int.

**Comment by dbarrosop** [comment]
That's great, note that the new testing framework has a method to compare objects. We could probably unify those. Let's discuss it when you send the PR

**Comment by GGabriele** [comment]
That's cool, I'm working on the config part now. It's really good that we're going to have `get_config` on all drivers as it will be really helpful for this.
